version: "3.8"

services:
  backend:
    build: .
    container_name: doctor-appointment-backend
    ports:
      - "5001:5000"
    depends_on:
      rabbitmq:
        condition: service_healthy # RabbitMQ sağlıklı olmadan başlamayacak
      redis:
        condition: service_started
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    networks:
      - app_network

  worker:
    build: .
    container_name: email-worker
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    command: ["node", "workers/emailWorker.js"]
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=465
      - SMTP_USER=ekursun3510@gmail.com
      - SMTP_PASS=yarx ctfh byzt linn
      - SMTP_SECURE=true
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-server
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" # RabbitMQ Management UI
    healthcheck: # Sağlık kontrolü eklendi
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
